### ISSUE TITLE
Safari Channel Order Helper

### ISSUE THREAD

**Issue by danrossi** [GoogleChrome/omnitone#10]
I'm not sure if this is correct but I believe something like this could help dynamically fix the safari channel order from the original channel map config. 

This Is what I have implemented according to the documentation. 

If this works would this be of interest to add as a global static util ?

```
OmnitoneUtils.channelMapSafari = function (channels) {
    channels.splice(0, 0, channels.splice(2, 1)[0]);
    return channels;
};
```

**Comment by hoch** [comment]
Thanks for your contribution, but this feature is already in the code:
https://github.com/GoogleChrome/omnitone#foadecoder
https://github.com/GoogleChrome/omnitone#foarouter

FYI, this is much faster than splicing array.

**Comment by danrossi** [comment]
Are you saying it  is ordering internally already for Safari sorry ? Or externally it is required to manually reorder for Safari depending what the custom channel order is ? 

It's confusing what is required in regards to that config that is all. 

I've implemented it here so the user doesn't have to do anything at all to treat it differently for Safari. I've tested Safari now and it seems to be working with the cors proxy of course and an mp4.

The demo video from the site seems to work across browsers but I hear phasing because the source is very noisy. So the noise floor is doubling which increases it's gain, then when rotating I can hear the phasing. It'a possibly self noise from a bad mic or preamp noise from low grade equipment. 

https://github.com/danrossi/three-vr-omnitone/blob/master/src/OmniToneAudio.js#L109

**Comment by hoch** [comment]
@danrossi You can do whatever you want in your package and I appreciate your effort on that. It is really nice to have a package that connects Omnitone and Three.js. However, I want to keep the channel rerouting option flexible within Omnitone. I don't want to make things special only for Safari.

Regarding the sound quality, I suggest you to file another entry for that. It is not relevant to this issue.

**Comment by danrossi** [comment]
That is what I'm trying to figure out and glean information from. 

The documentation is a little confusing. 

I'm remapping whatever is sent to it according to the order Safari needs. If that is wrong then it would be good to know although it seems to work. I don't believe there should be the need for two different configs if it can be done dynamically I think. 

The method was just a static helper method to be added to your library to be used externally on the channelMap config. Not remapped internally. That's perfectly fine mate !
