### ISSUE TITLE
Airplane example does not work

### ISSUE THREAD

**Issue by jaguarfi** [GoogleChrome/omnitone#101]
I tried to listen to the airplane example using the ambisonics configuration. But it does not work.

**Comment by hoch** [comment]
Can you elaborate? What do you mean by "it does not work"?  Can you also provide a link to the problem?

**Comment by jaguarfi** [comment]
It is working now. it maybe was a browser problem.
[https://rawgit.com/GoogleChrome/omnitone/master/examples/foa-renderer.html](url)

Thanks.
