### ISSUE TITLE
Not an issue but a request

### ISSUE THREAD

**Issue by Drumaddict182** [GoogleChrome/omnitone#29]
Hi everyone, 

I'm a sound designer for video games and 360 videos and I'm really interested in ambisonic audio. I'm trying to make a simple 360 video player that can also play ambix mixing. 

So i tried to make a video player in a html page by using the code that omnitone provide. But I'm really bad at coding so it doesn't work. 

And i also tried to copy the code from the demo page but it doesn't work locally.  

Is someone have already worked on a simple html page with a video ambix player ? Or can someone give me some advice to do this ?  

Sorry if I'm not clear enough about my request. Thanks a lot.

**Comment by hoch** [comment]
Can you explain your local set up?

https://github.com/GoogleChrome/omnitone/tree/gh-pages

Clone this branch and modify files with your content accordingly. That should work.

**Comment by Drumaddict182** [comment]
It works by changing media files with mine. Thanks a lot. You are a life saver.

**Comment by hoch** [comment]
Glad it worked out! Let me know if you have more feedback!
