### ISSUE TITLE
0.2.0 is broken on NPM

### ISSUE THREAD

**Issue by jwerle** [GoogleChrome/omnitone#39]
the `"main"` property in this projects [package.json](https://github.com/GoogleChrome/omnitone/blob/master/package.json#L5) file points to `src/main.js`. It should point to `build/omnitone.js` or `build/omnitone.min.js` so the module can be required correctly. Do you have a preference to which file in the `build/` directory that should be the "main" entry to the module?

cc @hoch

**Comment by jwerle** [comment]
I'm going to open a preliminary PR the points to `build/omnitone.js`.
cc @vipyne

**Comment by hoch** [comment]
Sure. I will take a look at the PR. I might have missed updating the package file.

**Comment by jwerle** [comment]
Great, thanks !
