### ISSUE TITLE
Output to AudioNode

### ISSUE THREAD

**Issue by brianchirls** [GoogleChrome/omnitone#4]
Is it possible to pass the output through another `AudioNode`? I like to use a single `GainNode` for muting and adjusting volume of the entire experience in one place.

**Comment by hoch** [comment]
This can be done, but not the intended usage. It might be better to have adjustable volume control in the virtual speaker array, so you can dynamically change the volume. Will add this in the next update.

**Comment by hoch** [comment]
Fixed with https://github.com/GoogleChrome/omnitone/pull/35. The new `FOARenderer` now behaves like an AudioNode. The README file will be updated accordingly.

See example [here](https://github.com/GoogleChrome/omnitone/blob/master/examples/foa-renderer.html).
