### ISSUE TITLE
XHR Error

### ISSUE THREAD

**Issue by Bartiff** [GoogleChrome/omnitone#47]
Hi,

There is a problem with this link ?
_https://raw.githubusercontent.com/google/spatial-media/master/support/hrtfs/cube/_

I had to replace with this (line 1050 in omnitone.js)
`var HRTFSET_URL = 'https://raw.githubusercontent.com/GoogleChrome/omnitone/master/src/resources/';`

**Comment by hoch** [comment]
Sorry for the late response. I should have coordinated more closely with the spatial media team before publishing the resources. I merged the patch from @zarov and will publish the updated NPM module as soon as possible.

Thanks for catching/reporting this!

**Comment by hoch** [comment]
The #48 and the version update (https://github.com/GoogleChrome/omnitone/releases/tag/0.2.2) fixed this issue. Closing.
