### ISSUE TITLE
'InsufficientQuota' error while accessing demo contents

### ISSUE THREAD

**Issue by winduptoy** [GoogleChrome/omnitone#5]
Demos on https://googlechrome.github.io/omnitone/#gallery don't load.

Seems like an App Engine over quota issue. When trying to load [https://storage.googleapis.com/omnitone-demo.google.com.a.appspot.com/resonance-1080p-h264-aac.mp4](https://storage.googleapis.com/omnitone-demo.google.com.a.appspot.com/resonance-1080p-h264-aac.mp4) I get `InsufficientQuota` error.

**Comment by hoch** [comment]
I think the coast is clear now. Can you try again?

**Comment by winduptoy** [comment]
@hoch Same deal even after a hard refresh.

<img width="1427" alt="screen shot 2016-07-26 at 11 36 17 am" src="https://cloud.githubusercontent.com/assets/270504/17144636/651620e0-5325-11e6-805b-001da8d6351b.png">

**Comment by hoch** [comment]
Are you still experiencing the issue?

**Comment by moxian** [comment]
Yes. I still get the following when trying to access https://storage.googleapis.com/omnitone-demo.google.com.a.appspot.com/resonance-1080p-h264-aac.mp4 :

`<?xml version='1.0' encoding='UTF-8'?><Error><Code>InsufficientQuota</Code><Message>The App Engine application does not have enough quota.</Message><Details>NOT_ENOUGH_QUOTA: App s~google.com:omnitone-demo does not have enough quota</Details></Error>`

**Comment by hoch** [comment]
The hard refresh won't help. It seems like we really are over the daily quota at certain time zones. I will check it out tomorrow again.

**Comment by beaufortfrancois** [comment]
For info, I'm still seeing the `InsufficientQuota` error in France now.

**Comment by hoch** [comment]
@beaufortfrancois Yes, I am still figuring out why this issue happens to visitors from a certain area. Thanks for following up!

**Comment by hoch** [comment]
I believe the issue is solved on the server side, but it might take hours to propagate all the changes. Can I ask you to try again in few hours?

**Comment by beaufortfrancois** [comment]
It works great! What a wonderful experience! Thanks!

**Comment by hoch** [comment]
@moxian @winduptoy Can you verify as well?

**Comment by winduptoy** [comment]
Works! Thanks!
