### ISSUE TITLE
Error using npm test

### ISSUE THREAD

**Issue by topherbuckley** [GoogleChrome/omnitone#51]
I am unable to run the npm test functionality as described in the readme. I'm running on Windows 10 using PowerShell. Here is the input and return I received. 

<code>PS D:\Downloads\omnitone-master\omnitone-master> npm test

> omnitone@0.2.2 test D:\Downloads\omnitone-master\omnitone-master
> node_modules/karma/bin/karma start

'node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.</code>

I opened up the node_modules/karma/bin/karma file and found it pretty empty other than:

<code>#!/usr/bin/env node

require('../lib/cli').run();</code>

I followed up and open the cli file, and did a text search for node_modules, and came up with zero results. Anyone else having this problem? I'd be happy to debug further if I'm not alone on this.

**Comment by hoch** [comment]
Not familiar with PowerShell and I don't have any Windows machine that I can test against, but I think you can try this and see if it works:

```
./node_modules/karma/bin/karma start
```

My guess is that PowerShell does not know what to do with the path.

**Comment by topherbuckley** [comment]
Thanks. I'll try that out tonight. May I ask which terminal you are using
for it to work? I have an ubuntu machine as well if you think I'd have
better luck on gnu-bash or otherwise.

**Comment by topherbuckley** [comment]
I tried 

<code>./node_modules/karma/bin/karma start</code>

and Windows opened the "How do you want to open this file" asking for which program to use to open some file. I guessed and used Chrome, but only received a plain text display of the contents of the karma file:

<code>#!/usr/bin/env node

require('../lib/cli').run();
</code>

I also tried using cmd.exe but got the same output. 

I'll try again on Ubuntu noting the #! notation, and not sure how Windows handles all this.  Or maybe I just need to know a bit more about NodeJS and am making some ignorant error?

**Comment by topherbuckley** [comment]
Tried on Ubuntu 16.04 using the gnu-bash terminal. Got this:

    node_modules/karma/bin/karma start

    START:

    24 05 2017 19:59:29.368:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:9876/

    24 05 2017 19:59:29.369:INFO [launcher]: Launching browser Chrome with unlimited concurrency

    24 05 2017 19:59:29.382:INFO [launcher]: Starting browser Chrome

    24 05 2017 19:59:29.383:ERROR [launcher]: No binary for Chrome browser on your platform.
  
    Please, set "CHROME_BIN" env variable.

    npm ERR! Test failed.  See above for more details.

Had to install the chromium-browser package through apt, and then set CHROME_BIN env variable via:


    export CHROME_BIN=chromium-browser

After that, I was able to run the npm test without issue. 

Also wanted to add that I needed to install the nodejs-legacy package via apt in order to get the karma script to call the correct version of "node". Otherwise NodeJS runs under the env name nodejs and the "node" env variable comes up missing. I recommend including the dependence on nodejs-legacy and chromium-browser packages in addition to running on the gnu-bash for the "npm test" to run properly in the readme (at least specific to Ubuntu 16.04). I'd be happy to update the readme via a pull request if you think that would be helpful. 

Feel free to close this issue.

**Comment by hoch** [comment]
Yes, I haven't tested the Karma system in Windows or Linux.

You've already found the fix and are I appreciated that you are willing to contribute your findings. I'll be happy to take a look at them. Feel free to create a PR!

**Comment by topherbuckley** [comment]
Did a fresh install of this and found a much better way to make this work using the latest version of NodeJS. Adding PR now.

**Comment by hoch** [comment]
Please take a look at #55.

I think Karma test is designed for CI, not multi-platform local testing. If we want to expand the scope of testing, that should be a separate issue.

**Comment by topherbuckley** [comment]
Alright. Sorry, I was confused on the use of Karma I guess.

I'll update issue #55 if I get the chance to figure out local installs on
Windows at a later date.
