### ISSUE TITLE
HRIR Link Broken

### ISSUE THREAD

**Issue by topherbuckley** [GoogleChrome/omnitone#54]
README.md contains a link to the HRIRs which appears to be broken. The link under questions is [THIS](https://github.com/google/spatial-media/tree/master/support/hrtfs/cube), which is under the FOADeocoder (Fully-configurable) heading. 

I noticed this hard link in a few other implementations of omnitone across the web and it always pops up in the web dev consoles as missing files. [HERE](https://github.com/google/spatial-media/tree/master/spatial-audio/raw-symmetric-cube-hrirs) has some of the same files, but not all that I see called for (e.g. E35.26_A135_D1.4.wav). 

The link for [THIS](https://cdn.rawgit.com/GoogleChrome/omnitone/962089ca/build/resources/sh_hrir_o_1.wav) still works, but it doesn't look like I can go digging around the directory structure to verify if the other files are there or not though.

**Comment by hoch** [comment]
Yes, it was a unfortunate decision made by me.

I have a plan to move all Omnitone's HRIRs to Google's static file server. Until then, all the HRIR files will be a part of Omnitone's own GitHub repository and I will keep monitoring them.

**Comment by hoch** [comment]
Closed by #56.
