### ISSUE TITLE
Localization Problems

### ISSUE THREAD

**Issue by topherbuckley** [GoogleChrome/omnitone#58]
I'm using [this setup](https://support.google.com/jump/answer/6399978?hl=en) to generate my ambisonics files, and pairing this with [this viewer](http://photo-sphere-viewer.js.org/)

Initially I thought things were working fine, but after playing around with the Ambix plugins within Reaper, and messing around with various locations on the sphere, I noticed some problems. 

<h2>The case where it works as expected:</h2>

- Position the mono source on either the left or right hand side of the sphere using the Ambix plugins in Reaper (exactly pointing to the middle of the left ear)

- Render to .wav as specified in google tutorial

- Load into the Photo-Sphere-Viewer

- Rotates well and auralizes in the expected location to the left or right as specified. 

<h2>The case where it fails:</h2>

- Position the mono source on the exact front or back of the sphere using the Ambix plugins in Reaper 

- Render to .wav as specified in google tutorial

- Load into the Photo-Sphere-Viewer

- Does not rotate or spatalize at all 

The rotation and spatalization within Reaper is working fine so I know its not that setup. Also if I import my exported Ambix file back into Reaper, I can control the yaw just fine, so it doesn't seem to be a problem with how I'm rendering the Ambix file either. 

Here is my omnitone init code:

```javascript
/**** Omnitone Code ****/
// Set up an audio element to feed the ambisonic source audio feed.
var audioElement = document.createElement('audio');
audioElement.src = 'audio/AmbisonicOcean.wav';

// Create AudioContext, MediaElementSourceNode and FOARenderer.
var audioContext = new AudioContext();
var audioElementSource =
    audioContext.createMediaElementSource(audioElement);
var foaRenderer = Omnitone.createFOARenderer(audioContext, {
    HRIRUrl: 'HRTFs/sh_hrir_o_1.wav'
  });

// Make connection and start play.
foaRenderer.initialize().then(function () {
    audioElementSource.connect(foaRenderer.input);
    foaRenderer.output.connect(audioContext.destination);
    audioElement.play();
  });

viewer.on('ready', function() {
  var camera = viewer.camera;
  // Rotate the sound field by passing Three.js camera object. (4x4 matrix)
  foaRenderer.setRotationMatrixFromCamera(camera.matrix);
  // foaDecoder.setRotationMatrixFromCamera(camera.matrix);
});

viewer.on('render', function() {
  foaRenderer.setRotationMatrixFromCamera(viewer.camera.matrix)
});
```
Any thoughts on what is going wrong? As it stands, I can't spatalize anything directly in front or behind the viewer.

**Comment by hoch** [comment]
So "the exact front or back of the sphere" is the problem. Right?

My speculation is:
1. The matrix transformation from Three.js 4x4 camera might be incorrect for some edge cases.
2. Somehow Omnitone's new IRs are not compatible with the audio rendered from Reaper/Ambix plug-in.

@drewbitllama @ mgorzel WDYT about the second point?

**Comment by mgorzel** [comment]
Re. 2, @topherbuckley could you check if the ambix_binaural_o1 plugin is definitely disabled on your master bus when you render to wav? From your description, is sounds like that could be the cause? Also, sharing the wavs could help to check if there is a problem with rendering? 

The new Omnitone's IRs should be 100% compatible with the Ambix encoder in Reaper.

**Comment by topherbuckley** [comment]
> So "the exact front or back of the sphere" is the problem. Right?

@hoch Yes, that is correct. 

I tested this more specifically just now and set the ambix_encoder to exact front (elevation=90, azimuth=-90)

![image](https://user-images.githubusercontent.com/15166572/27564366-1a4c3cde-5b12-11e7-85c4-2feab0c6044e.png)

Then I offset the azimuth by 1 degree to -89.

![image](https://user-images.githubusercontent.com/15166572/27564386-39335204-5b12-11e7-9e48-8c2f17dda433.png)

The exact front was completely unspatialized and the -89 degree one worked as expected. It does seem to be something wrong with the edge cases only. 

Also attached are the rendered audio from these test cases in the zip file. (AmbisonicSeagulls_Front.wav is the first case, and AmbisonicSeagulls_89FL.wav is the 2nd)

[audio.zip](https://github.com/GoogleChrome/omnitone/files/1103754/audio.zip)

@mgorzel I'm fairly new to using REAPER, so let me confirm what you are asking. I don't have any plugin/FX applied to the "Master Track". To check this, I click on the "FX" button on the MASTER on the bottom left of the screenshot. See screenshot below of this resulting empty FX dialog. Is this what you were talking about? 

![image](https://user-images.githubusercontent.com/15166572/27564096-727773da-5b10-11e7-90bb-fc4e87448c7f.png)

**Comment by topherbuckley** [comment]
@hoch You understand your code a lot better than I, but I'm curious why you think the matrix transformation from Three.js 4x4 camera might be incorrect for some edge cases, rather than some implementation in omnitone? 

My guess would be the camera matrix is working just fine, but that somewhere in the omnitone code there is some multiplication by zero. I say that because, in the edge cases, 2 out of 4 channels in the ambix file are null or filled with zeros.

**Comment by hoch** [comment]
@topherbuckley You got me wrong. I was saying my implementation of [this code](https://github.com/GoogleChrome/omnitone/blob/master/src/foa-renderer.js#L150) might be incorrect. I am also suspecting [this](https://github.com/GoogleChrome/omnitone/blob/61c03fa14959f26130b346911fe7fe0902501820/src/utils.js#L44) because it is the only place where multiplication is happening. So I will start from there when I have some time to work on it.

I would appreciate if you can provide minimum repro code or demo.

**Comment by topherbuckley** [comment]
@hoch I see. I will be busy with other things for the next few days, but I can help troubleshoot this and provide a demo of this issue later this week as well. 

From a quick look though, I'm doubting it is in that exports.invertMatrix4 method since it only appears to deal with the camera matrix which shouldn't change between the two cases. If the multiplication by zero is sneaking in there somewhere, it would have to deal with the zeros coming from the ambix file data. I'd be more apt to look towards the convolver perhaps? I need to look at the code more carefully, but I'd guess its a possibility that you are convolving some signal with one or both of the empty two channels in the edge cases, which would result in two empty output signals.

**Comment by mgorzel** [comment]
@topherbuckley, yes, that's what I mean - there should be no binaural plugin enabled during export, so it looks correct. I've also had a quick look at your WAV renders - they look OK. No signal in certain channels is expected when you pan your source so that it coincides with the directions of Cartesian axes.

However, when you say that your source is in the front, it is in fact on top of the listener. (+90 degrees elevation in Ambisonic convention is the top direction). That is why, if you have your sound source rendered like that and you are applying, rotation around the upward-facing axis (yaw), there should be no change in the binaural output. Could that be the case? The easiest way to check that would be to apply roll instead and listen if the source starts to move from one side to the other. Also, try to re-render your files setting the front position as 0az, 0el, and see if it works.

**Comment by topherbuckley** [comment]
@mgorzel You nailed it! That makes a LOT more sense. I was just interpreting the ambix encoder sphere completely wrong. I re-rendered with elv and azm = 0, (front) and it works just as well as the right or left sides (elv = 0 azm = 90/-90) 

Sorry for raising such a ruckus over my foolishness!

**Comment by hoch** [comment]
Thanks @mgorzel for finding the root cause of the issue!

**Comment by mgorzel** [comment]
NP! Glad that solved it!
