### ISSUE TITLE
Demo player does not work (Win 10, Chrome)

### ISSUE THREAD

**Issue by bryik** [GoogleChrome/omnitone#6]
![omnitone](https://cloud.githubusercontent.com/assets/12419712/17150711/7a34353e-533e-11e6-9b11-e3f6a9c9c70f.png)

I get the same error in Firefox as well.

Similar issue as ["Demo player doesn't work on Chrome OS"](https://github.com/GoogleChrome/omnitone/issues/1)?

**Comment by hoch** [comment]
Are you running this on Windows 32 bit?

**Comment by bryik** [comment]
Windows 10, 64 bit

**Comment by hoch** [comment]
Can you post the stack trace? (click the triangle on the left and copy-paste the error messages here.)

**Comment by rtoy** [comment]
I have the same problem  It comes from platform = ua.match(); it fails to match on my system. I'll get more detail when I try it out again on my system.

**Comment by hoch** [comment]
@bryik What is the result of this code in your console?

`window.navigator.userAgent`

**Comment by bryik** [comment]
Running that returns: 

`"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"`

Odd that you can't reproduce. I tried it on a friend's laptop (also Windows 10) and got the same error.

**Comment by hoch** [comment]
Yeap. That was it - there are some machine returns 'WOW64' in the UA string. The demo player cannot detect it at the moment. Now I know what to fix. Thanks!

**Comment by hoch** [comment]
@bryik Can you try the demo player with the fix? You might have to hard-refresh the browser to get the updated player.

**Comment by bryik** [comment]
It works!

Awesome demo BTW!
