### ISSUE TITLE
[hoa-staging] Use stereo audio files for convolver.

### ISSUE THREAD

**Issue by hoch** [GoogleChrome/omnitone#67]
The significant code of HOA, SOA support is actually splitting and merging HRIR files. Perhaps we should consider split them all into a pack of stereo files. This will reduce the setup time and the buffer duplication. For example:

- SOA
  - soa-1-2.wav, soa-3-4.wav, soa-5-6.wav, soa-7-8.wav, soa-9.wav
- HOA
  - hoa-1-2.wav, ..., hoa-15-16.wav

Also we do want to keep the information below in `src/resources`:

- README with the version of HRIR files.
- The original unsplitted version of HRIR files.

@drewbitllama WDYT?

**Comment by drewbitllama** [comment]
that can work. i think we should re-visit the original implementation once >8 channel count files are allowed.

**Comment by hoch** [comment]
I think this issue is orthogonal to the multichannel audio file issue. If we stick to the stereo files, it actually ensures the cross-browser support because all the browsers (including mobile ones) can decode it.

Can we have the original multichannel HRIR files (FOA, SOA, HOA) in our `src/resources`? Then I can write a script that generates a set of stereo files from the source.

**Comment by drewbitllama** [comment]
Sure. They should all be there already.

**Comment by hoch** [comment]
First of all, what's happening in Chrome M62 when you load up 112 audio files via XHR:

![screen shot 2017-08-22 at 12 26 47 pm](https://user-images.githubusercontent.com/676891/29583508-361daa02-8735-11e7-888e-6c8fa57c8a5a.png)

Chrome fires up 12 background threads to multiple decode files concurrently. So this means loading multiple stereo files instead of a big chunk of multichannel HRIR files would be better. With that said, there will be a very little improvement because the size of HRIR files is almost negligible.

The next example loads up ~1500 audio files. Chrome's still using 12 threads to decode. Just for fun.

![screen shot 2017-08-22 at 12 44 03 pm](https://user-images.githubusercontent.com/676891/29584137-a03e1d98-8737-11e7-8289-3266158778ed.png)

Secondly, this is what I would do in V1:

1. Use SOX to split up the original HRIR files into multiple stereo files.
2. Include SOX script in the repo for the CI testing.
3. Change the hoa-convolver code to use a set of stereo HRIR files without splitting/cloning buffers.

**Comment by hoch** [comment]
Closed with https://github.com/GoogleChrome/omnitone/commit/df28933fc66d26b491b838204426c43ce535bd7e.
