### ISSUE TITLE
copyToChannel is unsupported in Safari/Edge

### ISSUE THREAD

**Issue by felicialim** [GoogleChrome/omnitone#69]
When trying out HOA rendering with Songbird examples on Safari, we hit the following error:

TypeError: i.copyToChannel is not a function. (In 'i.copyToChannel(t.getChannelData(r),s+r)', 'i.copyToChannel' is undefined)

**Comment by drewbitllama** [comment]
Should we just swap it with getChannelData or is there more needed to resolve the Safari issue? Also, do you know if this related to the lack of support on iOS?

**Comment by hoch** [comment]
Yes, I am aware of this issue and kind of sad those two browsers are not really up-to-date. On FireFox, getChannelData() might behave funky once the buffer is used by other WebAudio nodes. copyToChannel() is a safe and recommended way of copying data without a race.

**Comment by hoch** [comment]
Also thanks @felicialim for bringing this up!

**Comment by hoch** [comment]
Fixed with https://github.com/GoogleChrome/omnitone/commit/77e26678a8d0d647a15f05fa8c58678a0bc61fc1.
