### ISSUE TITLE
Provide easy way to enable debug mode in demo player

### ISSUE THREAD

**Issue by follower** [GoogleChrome/omnitone#7]
It would be helpful to provide a way to enable debug mode from within the browser. e.g. Add a "try to play anyway" button to the toast message or enable the debug mode state to be specified in the URL.

The information regarding mobile browser support is currently fragmented and confusing. The main source seems to be https://github.com/GoogleChrome/omnitone/issues/2 which specifies:

> * Chrome for Android M51 does not support the multichannel audio decoding in MediaElement yet. However, the 4-channel audio stream can be decoded properly with the UnifiedMediaPipeline flag enabled.
> * Chrome for Android M53 (which is the dev channel ATM) supports the multichannel audio decoding by default, thus Omnitone can be used there without fiddling flags.

The Beta is currently M52 and the only reference to Unified Media Pipeline is a flag confusingly named "Disable Unified Media Pipeline" (with the option available to "enable" the disabling).

But after attaching a desktop debugger I was able to manually change the value of the player `debug` value to 'true' and the Resonance demo played successfully. (Highlight for me: following the sound of the clucking chickens. :) )

**Comment by hoch** [comment]
Fixed with ea1b7ba9e8a46265ea0624a6c4092285a7205b8b.

- Click `settings` icon in the gallery toolbar and you're in the debug mode.
- The demo player will be launched in the debug mode, that bypasses all the platform/device check and plays the content.
