### ISSUE TITLE
Code contains "let" which breaks (at least) uglify

### ISSUE THREAD

**Issue by jrylander** [GoogleChrome/omnitone#73]
The library contains the keyword "let" and that broke uglifyjs which does not understand es6. Maybe transpile with babel?

**Comment by hoch** [comment]
That's why it uses the beta version currently:
https://github.com/GoogleChrome/omnitone/blob/master/package.json#L25

This is because Omnitone coding style is enforced by Chrome/Google guideline.

**Comment by jrylander** [comment]
Ok. I am just running it through babel now for it not to crash on uglify but most importantly older browsers. Tnx for the code! My intention was not to nag, only to help :)

**Comment by hoch** [comment]
No worries. I am glad you brought this up - this record will help others who are wondering about `let` and `const`. :)
