### ISSUE TITLE
Thrown errors not catchable

### ISSUE THREAD

**Issue by otteroe** [GoogleChrome/omnitone#80]
On Mac OS 10_11 (El Capitan), safari 9 HRIR does not lead properly, but gives this error:

[Error] [Omnitone] HOARenderer: HRIR loading/decoding failed. (@658.19ms)

This is for both HOA and FOA, this in itself might not be an issue for this project, but I am unable to catch the error in any way.
The error is thrown during the initialize() method, since that is a promise, the .then(success, error) or .catch(error) should work. It does not.
When adding a `.then(function() {console.log('success'); }, function() {console.log('error'); });` to the initialize call, it prints nothing and the exception is thrown anyway.

When trying to provoke this behavior on another machine I called the renderer with hrirPathList that would fail, this resulted in another exception being called. The same behavior in not being able to catch the exception persists though.

Recreate this issue this way:
`
var foaRenderer = Omnitone.createFOARenderer(this.audioCtx, {hrirPathList: ['hello', 'path']});
foaRenderer.initialize().then(function() {
    console.log('Successful');
}, function(error) {
    console.log('error', error);
});
`

Expected result: 
`
[error] [Omnitone] BufferList: XHR error while loading "hello(Not Found)
[log] error false
`

Actual result:
`
[error] [Omnitone] BufferList: XHR error while loading "hello(Not Found)
`

**Comment by hoch** [comment]
Is this Safari specific?

Thanks for reporting and I'll investigate soon.

**Comment by otteroe** [comment]
Hrir loading/decoding is. But as I tried to specify, the issue of not receiving the exception is the bigger problem. And that can be provoked by providing faulty hrirPaths in the config.

Sorry if this was unclear.

**Comment by hoch** [comment]
> Hrir loading/decoding is

If the default HRIR is failing on Safari, I think that's a bigger issue for Omnitone. I assume you found this bug while trying custom HRIR files. 

From my experience, Safari's dev tool is not good at notifying users when a promise fails. With that said, I agree that we have a bug in the exception handling.

**Comment by otteroe** [comment]
Yes, but notice the version of Mac OS and safari this was tested on, it works fine on newer versions. No this was not found when testing custom hrir files, but when testing browser support.

**Comment by hoch** [comment]
Thanks! Would love to know about the result of the browser support testing.

**Comment by otteroe** [comment]
The browser testing is not as extensive as it perhaps should be. That older safari version is the only one so far.
