### ISSUE TITLE
Element has no supported sources

### ISSUE THREAD

**Issue by DrWig** [GoogleChrome/omnitone#9]
On Chrome on both Mac and PC clicking the play button on the simple demo.html example gives me:

"VM39 demo.html:44 Uncaught (in promise) DOMException: The element has no supported sources."
line 44: audioElement.play();

Demos on the omnitone website work fine, though....

**Comment by hoch** [comment]
How do you run the demo? You have to run the local web server on the root of the project directory.

**Comment by danrossi** [comment]
Run a python local server ie

```
python2.7 -m SimpleHTTPServer
```

**Comment by DrWig** [comment]
ah, ok.  Apologies!

cheers

Bruce

**Comment by DrWig** [comment]
and thanks, of course!

cheers

Bruce
