### ISSUE TITLE
Sound crackling with a html video element

### ISSUE THREAD

**Issue by youssinsa** [GoogleChrome/omnitone#93]
Hi !

Really nice work there.

I'm trying to use this in order to make a web player audio and video 360.

I was trying to use Omnitone with my audio files and there was no problem with that. 

Then, I added a html video tag to my html page in order to connect the video sound to Omnitone and spatialize it. The sound is effectively spatialized, but I can hear like it's "crackling", a little disturbing and irregular noise made its apparition.

I tried to treat a local audio file with Omnitone, adding a video tag with a local video file on the same page, and I can still hear the sound crackling. 

Moreover, even in a page with just a button to play an audio local file and an audiocontext (just like the foarenderer example), if I have to load another webpage in a new tab or window, there will be more crackling during the loading time. But with the FoaRenderer example online, I don't notice that.

Is this a known issue ? If not, there is a special way to treat the video element sound withtout any lost of quality ??

Thanks a lot !

**Comment by youssinsa** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Example: FOARenderer (Optimized)
    </title>
    <script src="https://www.gstatic.com/external_hosted/omnitone/build/omnitone.min.js"></script>
  </head>
  <body>
    <h1>
      Example: FOARenderer (Optimized)
    </h1>
    <p>
      <code>FOARenderer</code> is an optimized ambisonic renderer based on the
      integrated convolution (SH-MaxRe HRIR).
    </p>
    <p>
      See <a href="https://github.com/GoogleChrome/omnitone#foarenderer">more
      info</a> on <code>FOARenderer</code>.
    </p>


    <div id="video-container">
        <video controls>  
          <source src="videoSinusLeftAmbHackInversion.mp4" type="video/mp4">
          <p>Browser too old to support HTML5 video? How depressing!</p>
        </video>
    </div>


    <script>
    var foaRenderer;


    var onLoad = function () {
      var audioContext = new AudioContext();
      var audioElement = document.querySelector('video');
      var audioElementSource =
          audioContext.createMediaElementSource(audioElement);


      foaRenderer = Omnitone.createFOARenderer(audioContext, {
        channelMap: [0, 1, 2, 3]
      });


      foaRenderer.initialize().then(function () {
        audioElementSource.connect(foaRenderer.input);
        foaRenderer.output.connect(audioContext.destination);
      }, function (onInitializationError) {
        console.error(onInitializationError);
      });
    };

    window.addEventListener('load', onLoad);
    </script>
  </body>
</html>

**Comment by hoch** [comment]
Just curious. Have you tried with Chrome?

**Comment by youssinsa** [comment]
Nope, because we can't do it with local files using chrome

**Comment by hoch** [comment]
Revisiting this after few months. Do you still get noise from the local demo on FireFox? If local media playback is the only problem, I think it's rather related to FireFox.

**Comment by VijaiAaditya** [comment]
It's problem with playing local content. Host in iis or node server. I thiNk it should work.

**Comment by hoch** [comment]
I am closing this issue. Please re-open or create a new issue if needed.
