### ISSUE TITLE
Omnitone integration ES6

### ISSUE THREAD

**Issue by madox35** [GoogleChrome/omnitone#94]
Hello,

Is it possible to integrate Omnitone with ES6 ?
My issue : 

[!] Error: 'omnitone' is not exported by node_modules\omnitone\build\omnitone.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\js\linkAudio360.js (2:9)
1: import videojs from 'video.js';
2: import { omnitone } from 'omnitone';
            ^

also tried : import { * as Omnitone } from 'omnitone';
and : import Omnitone from 'omnitone';

But doesn't seems to work..

Any help?
Thanks in advance

[edit] : Last one seems to work but only like this : Omnitone.Omnitone.createFOARenderer...
Can it be written in another way ?

**Comment by hoch** [comment]
ES6 module is currently not supported, but I believe this is easy to fix.

**Comment by hoch** [comment]
After some exploration, I have decided to create two different types of library files:
1. omnitone.min.js (IIFE, just like old one)
2. omnitone.min.esm.js (ES6 module)
