### ISSUE TITLE
Error installing fsevents dependency

### ISSUE THREAD

**Issue by brianchirls** [GoogleChrome/omnitone#95]
This package includes an old version of fsevents as an optional dependency. I'm [unable to install](https://github.com/strongloop/fsevents/issues/229) that package on my version of OSX with the latest Node engine. It's not absolutely necessary, but it does screw things up. The issue I reference seems to be fixed with newer versions of fsevents. But it's an exact version match, so it won't upgrade automatically.

I can't figure out why this dependency is in here, since I don't see it referenced in any other code, unless it's vestigial and not really necessary.

Please upgrade the dependency version or remove it. Thank you.

**Comment by hoch** [comment]
I think it is a part of dependency chain of ESlint, which is required by GoogleChrome org. I will try to update the package info, but could you let me know your version of Node engine and OSX?

**Comment by brianchirls** [comment]
I'm running node v10.9.0 and OSX 10.13.6

I don't see it anywhere in the eslint dependency chain. It is in the chain for webpack, but I believe it should be a newer version.

Thanks.

**Comment by hoch** [comment]
Thanks for looking into it. I will have some time to tackle it in this week.
