### ISSUE TITLE
Documentation on supported media formats for HOA

### ISSUE THREAD

**Issue by bossesand** [GoogleChrome/omnitone#96]
As I come from the Audio and computer but  not  from a recent  programming or web development environment, I am finding it very difficult to find some information that I consider basic.
It probably is but still it is hard to find written down.

As having recorded Ambisonics during 10 years my technical/programming questions are these,:

-  is it mandatory for all audio only HOA media to by split in to no more than 8 channel files?
   My only indication that it is so is that omnitone enclosed files are split in that way!
   If so is there a function / module available that will hide this from a media creator?

-  When using omnitone in Firefox or Chrome what audio formats are then supported?
    I am mostly thinking of formats like Opus, vorbis-ogg and other compressed formats in addition to wav.

-   As a additional question, what is triggering the activation of HOA decoding in omnitone?
    I have found that 16 channel HOA files in wav, ogg and Opus files only decode the first 4 FOA channels.

**Comment by hoch** [comment]
> is it mandatory for all audio only HOA media to by split in to no more than 8 channel files?
> My only indication that it is so is that omnitone enclosed files are split in that way!

Can you elaborate? Do you have an example to demonstrate this problem?

> When using omnitone in Firefox or Chrome what audio formats are then supported?

Omnitone does not have dependency on particular audio file format. The audio stream is commonly served via `<audio>` or `<video>` elements and decoding capability of these features are up to the browser. Unfortunately the multichannel audio support on HTMLMediaElement is very different across browsers.

> As a additional question, what is triggering the activation of HOA decoding in omnitone?

Please take a look at the example code [here](https://github.com/GoogleChrome/omnitone/blob/master/examples/hoa-renderer.html). For HOA, you need to use a HOARenderer.

**Comment by bossesand** [comment]
https://github.com/GoogleChrome/omnitone/tree/master/examples/resources
Here are the example files that are Split to indicate that TOA files need sto be split...
I am using chrome and FF, 
I might be mistaken, and the only issue is that I do not have HOAencoder activated, 
If so I need a info on how to activate HOA deacoding, I do not read code fluently, I come more for the Ambisonic user side, I have been recording First order Ambisonics for 10 years with a Tetramic..
Now I want to use higher orders.,,

I have a few recordings in 9 and 16 channel files, second and third order, They do play but appearently only in foa, I am using a verison from Decembetr 2017 currently but will upgrade.

How do I activare HOAdecoding if it is not triggered by channel numbers?

I have also thestfiles in 4,9,16 channels with anouncements of channel numbers in each channel but only the first 4 can be heard, that was how I discovered that FOA was only used with higher order files.

**Comment by hoch** [comment]
> https://github.com/GoogleChrome/omnitone/tree/master/examples/resources
> Here are the example files that are Split to indicate that TOA files need sto be split...

Like I mentioned, some browsers are not capable of decoding multi-channel audio file that contains more than 9 channel. That's why we have 2 files.

> If so I need a info on how to activate HOA deacoding, I do not read code fluently, I come more for the Ambisonic user side, I have been recording First order Ambisonics for 10 years with a Tetramic..
Now I want to use higher orders.,,

That's fine. I understand your situation and I would like to help you get the right set up. That's why I suggested to use [this example](https://github.com/GoogleChrome/omnitone/blob/master/examples/hoa-renderer.html) as a starting point. If you can share an audio file (encoded in TOA), I can help you to create an example out of it.

> How do I activare HOAdecoding if it is not triggered by channel numbers?

You have to know what your encoded format is and you have to use HOARenderer object accordingly. The channel count does not trigger anything because it is not readily available to any APIs.

> I have also thestfiles in 4,9,16 channels with anouncements of channel numbers in each channel but only the first 4 can be heard, that was how I discovered that FOA was only used with higher order files.

This is possibly because you played those files through FOARenderer. Can you send me one of your example audio file?

**Comment by bossesand** [comment]
Hi
I will send you one small  file, which is not really ambisonics but will
prove to me that all 16 channels are rendered.
If you could do an example that plays that with the SOA render and the TOA
rendere that would be great.
I will send it in opus

Here is a link and info from the creator of the other 2 files I test with,
I can ask if it would be allowed to create a public coding example code
using these files linked to in below extract from sursound list

Best Regards Bo-Erik Sandholm

Each OctoMic and TetraMic is precisely and individually calibrated. Its
unique calibration correction file is applied during A- to B-format
encoding, using the supplied encoder plug-in.

(For TetraMic, the B-format file was encoded with VVAudio's Visual
Virtual Microphone v3.5. For OctoMic, the B-format file was encoded with
VVOctoEncodeH v1.0.0.)

TetraMic file:
   core-sound.com/temp/TetraMic-TotaPulchraEs-ambiX-excerpt.wav

OctoMic file:
   core-sound.com/temp/OctoMic-TotaPulchraEs-ambiX-O3-excerpt.wav

(You can see two photos of the recording session on Core Sound's
Facebook page.)


Len Moskowitz (moskowit@core-sound.com)
Core Sound LLC
www.core-sound.com
Home of OctoMic and TetraMic




Den tors 6 sep. 2018 kl 21:42 skrev Hongchan Choi <notifications@github.com

**Comment by bossesand** [comment]
Opus-America The Beautiful Octomic Second Order...
<https://drive.google.com/file/d/1FIwUXrB9kKFJEpBRqNWuqtY9MqURAI7G/view?usp=drive_web>

This is a second test file from Leonard that I have encoded in to Opus, He
Released it in wav but I cannaot finde the link at the moment....

BR Bo-Erik


Den tors 6 sep. 2018 kl 23:09 skrev Bo-Erik Sandholm <bossesand@gmail.com>:

**Comment by hoch** [comment]
I've sent you an email, but you can use this issue for the further discussion. The issue is more about the decoding functionality of browser rather than Omnitone.

**Comment by hoch** [comment]
Well, I sent the email to Len instead of you. :(

I made a working example out of the audio file you uploaded and it sounds okay, but I need to verify all the 16 channels are correctly streamed. This is because the opus format works a bit different way than others. (For example, Chrome's decodeAudioData() API could not decode your file whereas the audio element plays it fine.)

**Comment by bossesand** [comment]
If you resend  the new code to me I can try and see if I  understand ...

I do not if is relevant but I  believe that the sound files are handled
differently depending on how they are received by Chrome.

I think there is a different decoding if read as a file or loading as a
stream.

In one case the TOA file has to be split into 2 * 8channel files, in the
other it is read as a file and can be decoded as one 16 channel file.

My gui is presented from a local webserver written in JavaScript.

In my current effort I have a node.js module that presents a GUI for setup
of a BLE  connection to my headtracker for rotation of the sound field,
then browse to load a local multichannel file for playback.
And start/stop of playback.

At the moment I have only  foa decoding in omnitone so I can only hear
ambisonic decode of the first 4 channels, even if the file choosen is 9 or
16 channels.

Best Regards
Bo-Erik





Den 7 sep. 2018 18:38 skrev "Hongchan Choi" <notifications@github.com>:

Well, I sent the email to Len instead of you. :(

I made a working example out of the audio file you uploaded and it sounds
okay, but I need to verify all the 16 channels are correctly streamed. This
is because the opus format works a bit different way than others. (For
example, Chrome's decodeAudioData() API could not decode your file whereas
the audio element plays it fine.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleChrome/omnitone/issues/96#issuecomment-419496625>,
or mute the thread

**Comment by bossesand** [comment]
Great, is the same bug in Firefox I  wonder?
How about Vorbis would that work?
I know that new versions of libopus is suggested to support ambisonics as
opus audio tag 2 and 3... in the RC.

Bo-Erik


Den fre 7 sep. 2018 22:25Hongchan Choi <notifications@github.com> skrev:

**Comment by hoch** [comment]
In the meantime, try this example:
https://rawgit.com/GoogleChrome/omnitone/exp-opus-multichannel/examples/hoa-player.html

You can simply drag and drop whatever the file you want. (Of course it needs to be either SOA or TOA to function correctly.) I could play your Opus file with it easily.

> Great, is the same bug in Firefox I  wonder?

Not sure about FireFox, but @padenot could answer that question. (He's quite busy, but very attentive/responsive.)

> How about Vorbis would that work

You can try it for yourself with the player above and let me know.

> I know that new versions of libopus is suggested to support ambisonics as
> opus audio tag 2 and 3... in the RC.

@bitllama is the expert on the topic. FWIW, Even if libopus has the support for it, the actual plumbing within the browser is a different story. I am not sure where we stand now.

**Comment by bossesand** [comment]
Hi
Sorry for the delay, I have now tested, I consider the example Fully
working in Chrome!
Thank you for your assistance. I have tested and the results are below

https://rawgit.com/GoogleChrome/omnitone/exp-opus-multichannel/examples/hoa-player.html

8 channels of in OPUS and VORBIS in ogg
 - Plays   BUT, beware default Vorbis + Opus encoding LP filters 8th
channel - depending on encoder settings,
And channel ordering has to be taken in to account before sending to
decoder. if using mixed order

Wav 24bit 48kHz
16 toa channels = OK
9 soa channels = OK
8 soa channels = OK

Vorbis-ogg  libVorbis (20150105
16 channels = OK
9 channels = OK
8 soa channels = Plays - BUT, beware default Vorbis encoding LP filters
last channel - depending on encoder settings

Opus-ogg  libopus 1.1-170-g8046033
16 channels = OK
9 channels = OK

Opus-opus libopus 1.1-170-g8046033
16 channels = OK
9 channels = OK


Den fre 7 sep. 2018 kl 23:50 skrev Hongchan Choi <notifications@github.com>:

**Comment by padenot** [comment]
Firefox supports Opus with channel mapping family 0, 1, 2 and 255.

There is a maximum of two channels for mapping family 0, 8 for family 1, and 255 channels for mapping family 2 and 255 (per spec), but there are some rules on the number of channels. Let us know if it's not working for you (the example linked here seem to work well).

**Comment by hoch** [comment]
@bossesand Glad to head that it works okay! Omnitone currently doesn't support the mixed order, but you can easily reconfigure the channel mapping with Web Audio API's channel splitter/merger.

@padenot Thanks for following up! That's a nice information to have here in the issue tracker.
